version: "3.1"

services:
  backend_web:
    restart: always
    build:
      context: ./backend
      dockerfile: DockerfileWeb
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Misis_Kitties
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./backend/extra/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./app/data/pg/:/var/lib/postgresql/data/
    networks:
      - backend

  frontend_web:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "5173:80"

networks:
  backend:
    name: backend
  # fronted:
  #   name: frontend
